# Generated by Django 3.2.3 on 2021-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=[
                            ("UK", "United Kingdom"),
                            ("CZ", "Czech Republic"),
                            ("SK", "Slovakia"),
                        ],
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                ("date", models.DateField(verbose_name="Forecast Date")),
                ("avg_temp_c", models.FloatField(verbose_name="Temperature in Celsius")),
            ],
            options={
                "verbose_name": "Weather Forecast",
                "verbose_name_plural": "Weather Forecasts",
            },
        ),
    ]
